### ISSUE TITLE
es5-compatible build

### ISSUE THREAD

**Issue by duncanbeevers** [taskworld/test-bed#2]
Any chance this could be packaged for older node versions with a transpiled artifact?

For those of us sticking with LTM node versions it'd be nice to use this tool without too much hoop-jumping.

**Comment by dtinth** [comment]
Thanks for your interest in this project. 😄 

The runtime code is just ES5, so it should work all the way back to IE10, but no one’s using Node 4 anymore that Taskworld. That’s why we don’t support Node 4 right now. Sorry.

I want to avoid transpiled artifacts because we do a lot of experiments by `npm install`ing directly from Git. Unfortunately it skips all the transpilation process (IIRC).

I’d appreciate it if you could fix the syntax errors to make it compatible with Node 4.
I’d gladly accept a PR. 😃
